from django.conf import settings

OPEN_CHOICE_POLLS_QUESTION_ZFILL = getattr(settings, 'OPEN_CHOICE_POLLS_QUESTION_ZFILL', 3)

OPEN_CHOICE_POLLS_VOTER_PREFIX = getattr(settings, 'OPEN_CHOICE_POLLS_VOTER_PREFIX', 'anon')
OPEN_CHOICE_POLLS_VOTER_RANGE_START = getattr(settings, 'OPEN_CHOICE_POLLS_VOTER_RANGE_START', 20000)
OPEN_CHOICE_POLLS_VOTER_RANGE_END = getattr(settings, 'OPEN_CHOICE_POLLS_VOTER_RANGE_END', 20999)
