# Generated by Django 2.2.9 on 2020-02-08 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('open_choice_polls', '0001_initial'), ('open_choice_polls', '0002_question_slug'), ('open_choice_polls', '0003_auto_20200202_1950'), ('open_choice_polls', '0004_voter')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0, editable=False)),
                ('text', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Description (with basic markdown support)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('collection_start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Collection Phase')),
                ('collection_end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='End Collection Phase')),
                ('voting_start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Voting Phase')),
                ('voting_end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='End Voting Phase')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
                ('show_choices_approved', models.BooleanField(default=True, verbose_name='show approved choices')),
                ('show_choices_open', models.BooleanField(default=True, verbose_name='show unchecked choices')),
                ('show_choices_rejected', models.BooleanField(default=True, verbose_name='show rejected choices')),
                ('show_voting_results', models.BooleanField(default=True, verbose_name='show voting results before vote ends')),
                ('votes_per_session', models.PositiveSmallIntegerField(default=5, verbose_name='number of votes allowed per (cookie-based session)')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('choice_validation_hint', models.CharField(blank=True, max_length=200)),
                ('choice_validation_regex', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_slug', models.SlugField(blank=True, editable=False)),
                ('votes', models.IntegerField(default=0)),
                ('review_status', models.CharField(choices=[('APPROVED', '&#10004; (approved)'), ('OPEN', '&#63; (not yet reviewed)'), ('REJECTED', '&#10005; (rejected)')], default='OPEN', max_length=8, verbose_name='review status')),
                ('review_remark', models.CharField(blank=True, max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_choice_polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_code', models.CharField(blank=True, max_length=80)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
