# Generated by Django 2.2.9 on 2020-02-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0002_auto_20200209_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=False, help_text='Is participation (vote) allowed?')),
                ('votes_cast', models.PositiveIntegerField(default=0, help_text='Number of votes cast no Question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_choice_polls.Question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_choice_polls.Voter')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='voter_participation',
            field=models.ManyToManyField(through='open_choice_polls.Participation', to='open_choice_polls.Voter'),
        ),
    ]
