# Generated by Django 2.2.9 on 2020-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0003_add_participation_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='enrollment_code_valid_until',
            field=models.DateTimeField(blank=True, help_text='Leave empty for codes that never expire', null=True, verbose_name='Enrollment Code valid until'),
        ),
    ]
