# Generated by Django 2.2.9 on 2020-02-11 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('open_choice_polls', '0003_auto_20200202_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='choice',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_voter', models.BooleanField(default=False, editable=False, verbose_name='Is Voter?')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='Is Enrolled?')),
                ('enrollment_code', models.CharField(blank=True, editable=False, max_length=80, verbose_name='Enrollment Code')),
                ('enrollment_code_valid_until', models.DateTimeField(blank=True, help_text='Leave empty for codes that never expire', null=True, verbose_name='Enrollment Code valid until')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=False, help_text='Is participation (vote) allowed?')),
                ('votes_cast', models.PositiveIntegerField(default=0, help_text='Number of votes cast no Question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_choice_polls.Question')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_choice_polls.Voter')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='voter_participation',
            field=models.ManyToManyField(through='open_choice_polls.Participation', to='open_choice_polls.Voter'),
        ),
    ]
