# Generated by Django 2.2.9 on 2020-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0004_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='enrollment_code',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
