# Generated by Django 2.2.10 on 2020-02-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0005_add_flag_code_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
