# Generated by Django 2.2.9 on 2020-02-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0006_auto_20200207_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_voter',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
