# Generated by Django 2.2.9 on 2020-02-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0007_voter_is_voter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ('user',)},
        ),
        migrations.AlterField(
            model_name='voter',
            name='enrollment_code',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Enrollment Code'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_enrolled',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Enrolled?'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_voter',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Voter?'),
        ),
    ]
