# Generated by Django 2.2.9 on 2020-02-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_choice_polls', '0008_auto_20200207_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='is_enrolled',
            field=models.BooleanField(default=False, verbose_name='Is Enrolled?'),
        ),
    ]
